# Generated by Django 5.1.7 on 2025-04-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_groups_alter_users_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('idle', 'Idle'), ('dnd', 'Do Not Disturb'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
    ]
