# Generated by Django 5.1.7 on 2025-04-11 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_messages', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('time_stamp', models.DateTimeField(auto_created=True)),
                ('notify_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(verbose_name=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_messages.usermessages')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
