# Generated by Django 5.1.7 on 2025-04-25 01:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_alter_channels_options_alter_channels_channel_type_and_more'),
        ('friends', '0002_alter_friends_options_friends_created_at_and_more'),
        ('notifications', '0001_initial'),
        ('servers', '0002_alter_servers_options_servers_description_and_more'),
        ('user_messages', '0002_alter_usermessages_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-time_stamp'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AddField(
            model_name='notifications',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='channels.channels'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='content',
            field=models.TextField(default='Notification content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='friend_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='friends.friendrequest'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('mention', 'Mention'), ('friend_request', 'Friend Request'), ('server_invite', 'Server Invite'), ('server_event', 'Server Event')], default='Notification content', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.servers'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='title',
            field=models.CharField(default='message', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notifications',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_messages.usermessages'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
