# Generated by Django 5.1.7 on 2025-04-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_alter_servers_options_servers_description_and_more'),
        ('servers', '0002_serverrole_serverinvite'),
    ]

    operations = [
    ]
