# Generated by Django 5.1.7 on 2025-04-25 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_directmessagechannel'),
        ('user_messages', '0002_alter_usermessages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='dm_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='channels.directmessagechannel'),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='message_channel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='channels.channels'),
        ),
    ]
