# Generated by Django 5.1.7 on 2025-04-11 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('channel_type', models.CharField(max_length=60)),
                ('discord_server_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.servers')),
            ],
        ),
    ]
