# Generated by Django 5.1.7 on 2025-04-25 01:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('servers', '0002_alter_servers_options_servers_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channels',
            options={'verbose_name': 'Channel', 'verbose_name_plural': 'Channels'},
        ),
        migrations.AlterField(
            model_name='channels',
            name='channel_type',
            field=models.CharField(default='text', max_length=60),
        ),
        migrations.AlterField(
            model_name='channels',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='channels',
            name='discord_server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels_set', to='servers.servers'),
        ),
    ]
