# Generated by Django 5.1.7 on 2025-04-11 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('friends_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
                ('user_friend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='users.users')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests', to='users.users')),
            ],
        ),
    ]
